version: '3.9'
services:

  rubus:
    image: flyhead/rubus:2023.0.1
    ports:
      - "${RUBUS_HOST_PORT}:8501"
    environment:
      - BUILD=flyhead/rubus:2023.0.1
      - PYTHONPATH=/usr/local/src/Rubus
    volumes:
      - .:/usr/local/src/Rubus
      - ${RUBUS_TRACKLOGS_DIR}:/usr/local/src/Rubus/tracklogs
      - ${RUBUS_CONFIGURATIONS_DIR}:/usr/local/src/Rubus/configurations
    command: "streamlit run app.py"
