version: '3.9'
services:

##############################
#  Run container
#  - Run
#  - mount volumes "rubus_data" in Docker
# $ docker-compose -f docker-compose.yml up -d rubus
####################
  rubus:
    image: flyhead/rubus:2023.0.2
    ports:
      - "8501:8501"
    environment:
      - BUILD=flyhead/rubus:2023.0.2
      - PYTHONPATH=/usr/local/src/Rubus
    volumes:
      - rubus_data:/usr/local/src/Rubus
    command: "streamlit run app.py --server.headless true --server.fileWatcherType none --browser.gatherUsageStats false"

volumes:
  rubus_data: